import { initializeApp } from "https://www.gstatic.com/firebasejs/11.8.1/firebase-app.js";
import { getFirestore, doc, setDoc, onSnapshot, serverTimestamp } from "https://www.gstatic.com/firebasejs/11.8.1/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyC0kLLCn54MzKQFEFTCXgN6jNqYqCoVw8Q",authDomain:"checkobrav9.firebaseapp.com",projectId:"checkobrav9",storageBucket:"checkobrav9.firebasestorage.app",messagingSenderId:"604869399584",appId:"1:604869399584:web:a43c932c2c907ec275d845",measurementId:"G-YB2LTJ9MWM"};
let db=null, cloudReady=false;
try{const app=initializeApp(firebaseConfig);db=getFirestore(app);cloudReady=true;console.log('✅ Firebase conectado V11.2')}catch(e){console.warn('Firebase no disponible',e)}

const users=[
{id:'nicole',name:'Nicole Jaques Olivera',role:'Supervisora',profile:'supervisor',pass:'Castellon227@',works:['Cerámicos Piso','Cerámicos Muro','Cerámicos Rasgos Ventana','Impermeabilización Baños','Cornisas','Marcos de Puerta']},
{id:'jose',name:'José Labraña',role:'Supervisor',profile:'supervisor',pass:'Castellon227@',works:['Tabiquería Perimetral','Volcopanel','Shaft','Vigones','Dinteles','Prueba de Presión']},
{id:'paulina',name:'Paulina Cruces',role:'Supervisora',profile:'supervisor',pass:'Castellon227@',works:['Terminación Gruesa','Trazado de Tabiques','Rasgos de Ventana']},
{id:'vicente',name:'Vicente Bizama',role:'Control de Calidad',profile:'calidad',pass:'Castellon227@',works:['Calidad']},
{id:'gonzalo',name:'Gonzalo Riquelme',role:'Jefe de Terminaciones',profile:'gonzalo',pass:'Castellon227@',works:['Gestión Terminaciones']},
{id:'cristobal',name:'Cristóbal',role:'Administrador de Obra',profile:'admin',pass:'Castellon227@',works:['Administración']},
{id:'paul',name:'Paul González',role:'Jefe de Terreno General',profile:'terreno',pass:'Castellon227@',works:['Terreno']},
{id:'constanza',name:'Constanza Reyes',role:'Oficina Técnica',profile:'oficina',pass:'Castellon227@',works:['Planos','RDI','Fichas Técnicas','Comunicados Técnicos']}
];
const canAssign=['vicente','gonzalo','cristobal','paul'];
const canCreatePapa=['gonzalo','cristobal','paul'];
const typeRooms={A:['Cocina','Baño','Dormitorio','Terraza'],B1:['Cocina','Estar','Dormitorio','Baño','Terraza'],D:['Cocina','Estar','Terraza','Dormitorio 1','W Closet 1','Baño 1','Dormitorio 2','W Closet 2','Baño 2'],C:['Estar','Cocina','W Closet','Baño','Dormitorio','Terraza'],B:['Cocina','Estar','Closet','Dormitorio','Baño','Terraza'],A1:['Cocina','Baño','Dormitorio','Terraza']};
const typeByCol={1:'A',2:'B1',3:'D',4:'C',5:'B',6:'A1'};
const areaByType={A:'28,66 m²',B1:'35,35 m²',D:'48,54 m²',C:'33,74 m²',B:'34,82 m²',A1:'Pendiente m²'};
const allParts=['Rasgos de Ventana','Terminación Gruesa','Trazado de Tabiques','Tabiquería Perimetral','Volcopanel','Prueba de Presión','Impermeabilización Baños','Marcos de Puerta','Cerámicos Piso','Cerámicos Muro','Cerámicos Rasgos Ventana','Cornisas','Pintura','Shaft','Vigones','Dinteles'];
const deptLevelParts=['Rasgos de Ventana','Terminación Gruesa','Trazado de Tabiques','Tabiquería Perimetral','Volcopanel','Shaft','Dinteles','Prueba de Presión','Marcos de Puerta','Cerámicos Piso','Cerámicos Rasgos Ventana','Cornisas','Pintura'];
const roomLevelParts=['Cerámicos Muro','Impermeabilización Baños'];
const stateOrder=['Sin iniciar','En ejecución','Ejecutada','Validada Calidad','Observada'];
const stateClass={'Sin iniciar':'gray','En ejecución':'yellow','Ejecutada':'blue','Validada Calidad':'green','Observada':'red'};
const dependencies={
'Terminación Gruesa':['Rasgos de Ventana'],
'Trazado de Tabiques':['Terminación Gruesa'],
'Tabiquería Perimetral':['Trazado de Tabiques'],
'Volcopanel':['Trazado de Tabiques'],
'Prueba de Presión':['Tabiquería Perimetral','Volcopanel'],
'Impermeabilización Baños':['Prueba de Presión'],
'Marcos de Puerta':['Tabiquería Perimetral','Volcopanel','Prueba de Presión'],
'Cerámicos Piso':['Tabiquería Perimetral','Volcopanel','Marcos de Puerta'],
'Cerámicos Muro':['Tabiquería Perimetral','Volcopanel','Marcos de Puerta','Impermeabilización Baños'],
'Cerámicos Rasgos Ventana':['Tabiquería Perimetral','Volcopanel','Marcos de Puerta'],
'Cornisas':['Cerámicos Piso','Cerámicos Muro'],
'Pintura':['Cornisas']
};
const checklist={
'Rasgos de Ventana':['Sin nidos ni fierros a vista','Superficie limpia y seca','Rasgo según plano','Espuma poliuretano retirada','Pendiente inferior corregida','Hidrofugado ejecutado','Medidas de vano verificadas','Plomos y escuadras revisados'],
'Terminación Gruesa':['Retiro de agujas y piezas de moldaje','Retiro de clavos, alambres y dowels','Descarachado y rinconeo','Tapado de agujas','Reparación de segregaciones','Óxidos tratados','Planeidad revisada','Cuadratura revisada','Limpieza final del frente'],
'Trazado de Tabiques':['Superficie limpia','Trazado según plano vigente','Canal estructura marcado','Tabique terminado marcado','Trazo subido a cielo','Vanos identificados','Medidas verificadas','Cuadratura verificada'],
'Tabiquería Perimetral':['Sonoglass en solera piso','Sonoglass en solera cielo','Montantes según EETT','Refuerzos instalados','Primera cara separada del piso','Fijaciones correctas','Planitud revisada','Escuadra revisada','Instalaciones previas revisadas antes de cierre'],
'Volcopanel':['Rectificación trazo','Instalación eléctrica','Instalación sanitaria','Cuñas instaladas','Alineadores instalados','Sello espuma máximo 2 cm','Eliminación de excesos'],
'Prueba de Presión':['Sector identificado','Instalación llena y presurizada','Presión inicial registrada','Tiempo de prueba cumplido','Presión final registrada','Sin fugas visibles','Registro fotográfico','Registro firmado'],
'Impermeabilización Baños':['Superficie limpia y seca','Sello perimetral ejecutado','Cordón Sika en uniones','Geotextil continuo en juntas','Encuentro muro-piso reforzado','Pasadas reforzadas','Primera mano completa','Segunda mano completa','Sin poros ni zonas descubiertas'],
'Marcos de Puerta':['Vanos conformes','Marcos aplomados','Marcos escuadrados','Diagonales verificadas','Fijaciones instaladas','Marco inmovilizado durante curado','Espuma uniforme','Sin deformación post curado','Sin golpes ni daños visibles'],
'Cerámicos Piso':['Superficie limpia, firme y nivelada','Tonalidad y calibre verificados','Adhesivo correcto según sustrato','Cantería uniforme','Diferencia de nivel verificada','Contacto adhesivo-palmeta verificado','Sin palmetas quebradas o despuntadas','Sin palmetas sopladas','Fragüe uniforme','Limpieza final conforme'],
'Cerámicos Muro':['Superficie limpia y aplomada','Alineación vertical y horizontal','Cortes superiores y encuentros conformes','Cantería uniforme','Encuentros limpios','Sin piezas quebradas o despuntadas','Sin piezas sopladas','Fragüe uniforme','Terminación visual conforme'],
'Cerámicos Rasgos Ventana':['Cantería uniforme en rasgos','Cortes alineados','Encuentro con marco limpio','Adhesión correcta','Fragüe uniforme','Sin piezas quebradas','Terminación de esquinas correcta','Sin desprendimientos','Terminación estética conforme'],
'Cornisas':['Trazo verificado','Adhesivo de montaje aplicado','Continuidad visual','Uniones alineadas','Juntas controladas','Nivelación revisada','Cortes de remate conformes','Sin separaciones visibles','Sin fisuras ni desprendimientos','Encuentros limpios'],
'Pintura':['Superficie limpia y seca','Reparaciones previas terminadas','Lijado conforme','Sellador o aparejo aplicado según procedimiento','Primera mano uniforme','Segunda mano uniforme','Sin chorreaduras','Sin diferencias visibles de tono','Encuentros y cortes limpios','Terminación final conforme'],
'Shaft':['Sonoglass en perímetro','Planitud revisada','Escuadra revisada','Registro correctamente posicionado','Sellos conformes','Terminación limpia'],
'Vigones':['Altura conforme','Alineamiento conforme','Escuadra conforme','Planitud conforme','Encuentro con tabiquería conforme'],
'Dinteles':['Altura conforme','Alineamiento conforme','Escuadra conforme','Refuerzos instalados','Terminación limpia']
};
const library={
'Rasgos de Ventana':{doc:'PT-TERM-13 Rasgos de Ventanas + Manual de Tolerancias',inst:['Huincha','Regla de aluminio','Nivel','Escuadra','Plomo o nivel láser','Linterna'],tol:['Medidas del vano contra plano: ±5 mm','Desaplome/plomo recomendado: ±2 mm/m','Escuadra: 3 mm a los 40 cm','Superficie firme, limpia y sin zonas sopladas','Pendiente inferior ejecutada correctamente','Terminación uniforme'],fullTol:['Medidas de largo, alto y ancho del vano: controlar contra plano y EETT.','Desviación de plomo y escuadra: controlar antes de instalar ventana o remate.','La superficie no debe presentar nidos, fierros expuestos, zonas sueltas o sopladas.','La pendiente inferior debe permitir escurrimiento y evitar acumulación de agua.'],method:['Medir alto, ancho y profundidad del vano.','Controlar plomo y escuadra con nivel o láser.','Revisar superficie con inspección visual y golpe suave.','Verificar pendiente inferior y continuidad de hidrofugado.'],err:['No retirar espuma o material sobrante','Hidrofugar sin superficie seca','Pendiente inferior deficiente','No controlar descuadres antes del avance siguiente'],tip:'Un rasgo correcto puede hacer que una ventana se vea bien instalada; un rasgo defectuoso puede hacer que una ventana correcta parezca mala.'},
'Terminación Gruesa':{doc:'PT-OG-06 Terminación Gruesa + Manual de Tolerancias',inst:['Regla de aluminio 2 m','Nivel láser','Plomo','Escuadra','Huincha','Linterna'],tol:['Planeidad base con regla: ±5 mm','Verticalidad/desaplome de paramentos: ±2 mm/m','Cuadratura de encuentros: 3 mm a los 40 cm','Agujas, moldajes, clavos, alambres y dowels retirados','Segregaciones reparadas','Óxidos tratados','Planeidad y cuadratura verificadas','Centros e instalaciones revisados'],fullTol:['Las superficies deben quedar aptas para recibir trazado y partidas posteriores.','Planeidad, verticalidad y cuadratura deben revisarse antes de liberar el frente.','Los defectos superficiales visibles deben ser reparados antes de avanzar a trazado.'],method:['Recorrer el departamento completo.','Controlar muros, cielos y encuentros con regla y nivel.','Verificar retiro de elementos embebidos o sobresalientes.','Registrar nidos, fisuras, óxidos o segregaciones antes de liberar.'],err:['Liberar con restos de moldaje','No tratar óxidos','Dejar segregaciones sin reparar','No limpiar antes del trazado'],tip:'Una mala base multiplica los errores en todas las partidas posteriores.'},
'Trazado de Tabiques':{doc:'PT-TERM-02 Trazado de Tabiques',inst:['Huincha','Tiralíneas','Nivel láser','Escuadra','Plano vigente','Marcadores de color'],tol:['Medidas de recintos verificadas','Medidas de vanos verificadas','Cuadratura controlada','Trazo subido a cielo','Vanos identificados'],fullTol:['Medidas de recintos y vanos: ±5 mm según criterio de procedimiento cargado.','Cuadratura de recintos: ±5 mm según procedimiento cargado.','El trazado debe corresponder a plano vigente y referencias oficiales.'],method:['Confirmar plano vigente.','Medir desde ejes o referencias oficiales.','Marcar canal de estructura y tabique terminado.','Subir trazo a cielo.','Verificar vanos y cuadratura antes de liberar tabiquería.'],err:['Medir desde referencia incorrecta','No subir trazo a cielo','No identificar vanos','No controlar cuadratura antes de instalar'],tip:'El trazado correcto evita correcciones caras cuando el tabique ya está instalado.'},
'Tabiquería Perimetral':{doc:'Checklist interno tabiquería perimetral + EETT',inst:['Huincha','Nivel','Regla de aluminio','Escuadra','Atornillador con control','Linterna'],tol:['Desaplome máximo: ±5 mm piso-cielo','Planeidad tabique sin huinchas: ±5 mm','Planeidad tabique terminado: ±3 mm','Cuadratura: 3 mm a los 40 cm','Montantes cada 40 cm o según EETT','Separación plancha-piso: 1 cm'],fullTol:['Desaplome/verticalidad máxima: ±5 mm entre piso y cielo.','Planeidad de tabique sin huinchas: ±5 mm.','Planeidad de tabique terminado: ±3 mm.','Cuadratura tabique-tabique o tabique-cielo: 3 mm a los 40 cm.','Montantes cada 40 cm o según EETT aplicable.','Plancha separada 1 cm del piso según criterio cargado.','Separación superior contra losa según procedimiento.','Refuerzos deben quedar antes del cierre de planchas.'],method:['Verificar soleras y sello antes de cerrar.','Medir separación de montantes.','Confirmar refuerzos por arquitectura y especialidades.','Controlar planitud y escuadra.','Revisar instalaciones antes de cerrar la cara final.'],err:['Cerrar sin revisar instalaciones','Olvidar refuerzos','Montantes fuera de modulación','Material mal acopiado','Plancha apoyada directamente al piso'],tip:'Un tabique fuera de plomo afecta puertas, muebles, cerámicos y terminaciones.'},
'Volcopanel':{doc:'Procedimiento Volcopanel + Manual de Tolerancias',inst:['Huincha','Nivel láser','Regla de aluminio','Escuadra','Plomo'],tol:['Rectificación de trazo: ±5 mm','Alineación general: ±5 mm','Desaplome máximo: ±5 mm piso-cielo','Sello espuma: máximo 2 cm','Eliminar excedentes de espuma y material'],fullTol:['El trazo debe verificarse antes de fijar paneles.','Las instalaciones eléctrica y sanitaria deben quedar revisadas antes de cerrar.','Las cuñas y alineadores deben asegurar plomo y continuidad.','El sello de espuma no debe superar 2 cm y debe quedar sin excesos.'],method:['Rectificar trazo contra plano vigente.','Verificar instalaciones antes de cierre.','Controlar cuñas y alineadores.','Medir sello espuma y retirar excedentes.'],err:['Cerrar sin revisar instalaciones','Dejar sello espuma excesivo','No eliminar excedentes','No controlar plomo antes de avanzar'],tip:'El Volcopanel debe revisarse antes de cerrar; después las correcciones son más lentas y visibles.'},
'Prueba de Presión':{doc:'Procedimiento de control de instalaciones',inst:['Manómetro','Cronómetro','Huincha o identificación de sector','Cámara','Registro de prueba'],tol:['Presión inicial registrada','Tiempo de prueba cumplido','Presión final registrada','Sin pérdida de presión','Sin fugas visibles','Registro firmado o fotografiado'],fullTol:['La presión inicial y final deben quedar registradas.','No debe existir pérdida de presión ni fuga visible durante el tiempo de prueba.','El sector probado debe quedar claramente identificado.'],method:['Identificar sector y cerrar circuito.','Llenar y presurizar instalación.','Fotografiar presión inicial.','Esperar tiempo definido por procedimiento.','Fotografiar presión final y revisar fugas.'],err:['No fotografiar manómetro','No identificar sector','No cumplir tiempo mínimo','Aceptar pequeñas fugas','No dejar registro firmado'],tip:'Una prueba bien registrada evita discusiones posteriores y protege al equipo ante fallas futuras.'},
'Impermeabilización Baños':{doc:'Procedimiento de impermeabilización + Manual de Tolerancias',inst:['Huincha','Linterna','Rodillo o brocha de control','Peineta/medidor de espesor si aplica','Cámara'],tol:['Superficie limpia y seca','Continuidad de membrana','Encuentros reforzados','Pasadas reforzadas','Sin poros ni zonas descubiertas','Manos completas según procedimiento'],fullTol:['La membrana debe ser continua.','Los encuentros muro-piso y cambios de plano deben quedar reforzados.','No deben existir poros, cortes ni zonas sin cobertura.','La superficie debe estar seca y libre de polvo antes de aplicar.'],method:['Revisar limpieza y sequedad antes de aplicar.','Verificar refuerzos en esquinas y pasadas.','Controlar continuidad después de cada mano.','Registrar zonas reparadas antes de liberar cerámicos.'],err:['Aplicar sobre polvo o humedad','Cortar geotextil en esquinas','No reforzar pasadas','Dejar poros','Liberar sin revisar continuidad'],tip:'La mayoría de las filtraciones nace en encuentros, pasadas y cambios de plano, no en el centro del paño.'},
'Marcos de Puerta':{doc:'Procedimiento de puertas y marcos + Manual de Tolerancias',inst:['Huincha','Nivel','Plomo','Escuadra','Regla','Laina o galga'],tol:['Plomo máximo recomendado: ±3 mm','Escuadra máxima recomendada: ±3 mm','Diagonales sin diferencia mayor a 3 mm','Verticalidad verificada por ambos lados','Horizontalidad superior conforme','Ancho superior, medio e inferior medido','Altura en extremos y centro medida','Diagonales verificadas','Sin deformación post curado'],fullTol:['Controlar plomo en ambos sentidos.','Controlar escuadra mediante diagonales.','Medir ancho superior, medio e inferior.','Medir alto en ambos extremos y centro.','El marco no debe deformarse durante el curado.'],method:['Medir vano antes de instalar.','Verificar plomo, nivel y escuadra.','Medir diagonales.','Controlar fijaciones y estabilidad.','Revisar nuevamente después del curado.'],err:['Confiar solo en espuma','No revisar diagonales','Retirar fijaciones antes del curado','Aceptar marco con deformación','No controlar ancho en tres puntos'],tip:'La mayoría de las puertas que rozan no tienen un problema en la hoja, sino en el marco.'},
'Cerámicos Piso':{doc:'Manual CDT Revestimientos Cerámicos + Procedimiento de instalación',inst:['Regla de aluminio 2 m','Nivel','Galga','Huincha','Elemento para inspección sonora','Linterna'],tol:['Diferencia de nivel máxima 1 mm','Alineación de canterías controlada','Espesor de cantería uniforme','Contacto adhesivo-palmeta mínimo 70%','Sin palmetas quebradas, despuntadas o agrietadas','Sin diferencias evidentes de tono'],fullTol:['Diferencia de nivel en piso: máximo 1 mm según criterio cargado en app.','Alineación de canterías: ±2 mm en 3 m según criterio cargado.','Espesor de canterías: ±2 mm según criterio cargado.','Contacto adhesivo-palmeta: mínimo 70% según criterio cargado.','Palmetas quebradas, despuntadas, agrietadas o sin esmalte: no aceptadas.','Variación de tonalidad o defectos de aspecto: controlar según Manual CDT.'],method:['Controlar superficie antes de fraguar.','Revisar nivel y planeidad con regla.','Controlar canterías visualmente y con galga.','Realizar inspección sonora para detectar soplado.','Revisar cortes, encuentros y limpieza final.'],err:['Palmetas sopladas','Diferencia de tono','Canterías abiertas','Desniveles entre piezas','Fragüe irregular','Cortes mal ubicados'],tip:'Una cantería visualmente alineada puede ocultar una mala planeidad; revisa primero planeidad y luego alineación.'},
'Cerámicos Muro':{doc:'Manual CDT Revestimientos Cerámicos + Procedimiento de instalación',inst:['Regla de aluminio','Nivel','Escuadra','Galga','Huincha','Linterna'],tol:['Diferencia de plano máxima 2 mm','Alineación vertical y horizontal controlada','Espesor de cantería uniforme','Sin palmetas quebradas, despuntadas o agrietadas','Encuentros y cortes limpios','Fragüe uniforme'],fullTol:['Muros y otras superficies: diferencia máxima 2 mm según criterio cargado.','Alineación de canterías: ±2 mm en 3 m según criterio cargado.','Espesor de canterías: ±2 mm según criterio cargado.','Palmetas quebradas, despuntadas, agrietadas o sin esmalte: no aceptadas.','Defectos de aspecto visibles deben revisarse según Manual CDT.'],method:['Revisar aplome y planeidad de superficie.','Controlar alineación de canterías verticales y horizontales.','Revisar cortes y encuentros.','Controlar fragüe y limpieza.','Inspeccionar visualmente con luz lateral.'],err:['Desalineación vertical','Cortes irregulares','Cantería variable','Piezas despuntadas','Fragüe manchado','Diferencia de tono'],tip:'En muros, el ojo detecta rápidamente líneas verticales fuera de alineación, especialmente cerca de artefactos y esquinas.'},
'Cerámicos Rasgos Ventana':{doc:'Manual CDT Revestimientos Cerámicos + Procedimiento de instalación',inst:['Regla','Nivel','Galga','Huincha','Escuadra','Linterna'],tol:['Diferencia de plano máxima: 2 mm','Alineación de canterías: ±2 mm en 3 m','Espesor de cantería: ±2 mm','Cortes alineados','Cantería uniforme','Encuentro con marco limpio','Sin piezas quebradas','Sin desprendimientos','Fragüe uniforme'],fullTol:['Aplicar criterios de revestimiento cerámico: alineación, cantería, aspecto, adherencia y ausencia de daños.','Los encuentros con marcos deben quedar limpios y sin piezas sueltas.','No se aceptan piezas quebradas, agrietadas o despuntadas.'],method:['Revisar continuidad visual del rasgo.','Controlar cortes y encuentros con marco.','Verificar adherencia y sonido.','Revisar fragüe y esquinas.'],err:['Cortes desalineados','Encuentros sucios','Piezas pequeñas mal rematadas','Fragüe irregular','Desprendimientos'],tip:'Los rasgos de ventana son zonas muy visibles para el cliente porque reciben luz directa.'},
'Cornisas':{doc:'Procedimiento instalación de cornisas + Manual de Tolerancias',inst:['Nivel','Regla','Huincha','Linterna','Escuadra'],tol:['Alineación de juntas controlada','Nivelación controlada','Cortes de remate conformes','Continuidad visual','Sin separaciones visibles','Sin fisuras ni desprendimientos'],fullTol:['Alineación de juntas: 1 mm según criterio cargado.','Nivelación: 3 mm/m según criterio cargado.','Cortes de remate: mínimo 30 cm según criterio cargado.','La continuidad visual y encuentros deben revisarse antes de liberar terminación.'],method:['Revisar trazo y nivelación.','Controlar uniones y encuentros.','Revisar continuidad visual con luz lateral.','Verificar cortes y remates.','Controlar fisuras, separaciones y desprendimientos.'],err:['Instalar sin trazo','Juntas visibles','Encuentros abiertos','Cortes muy cortos','Desniveles visibles','Fisuras posteriores'],tip:'Las sombras revelan desniveles y juntas que muchas veces no se ven durante la instalación.'},
'Pintura':{doc:'Procedimiento de pintura + Manual de Tolerancias',inst:['Luz rasante','Linterna','Regla','Lija de control','Huincha','Cinta de enmascarar'],tol:['Superficie uniforme','Sin chorreaduras','Sin marcas de rodillo visibles','Sin diferencias evidentes de tono','Encuentros limpios','Reparaciones previas no visibles'],fullTol:['La superficie debe quedar homogénea bajo iluminación normal de uso.','No deben existir chorreaduras, marcas evidentes, manchas ni diferencias de tono.','Los encuentros con otros elementos deben quedar limpios y definidos.'],method:['Revisar superficie antes de pintar.','Controlar lijado y sellado.','Revisar primera mano antes de segunda.','Inspeccionar con luz natural y luz rasante.','Controlar encuentros, esquinas y reparaciones.'],err:['Pintar sobre polvo','No lijar reparaciones','Diferencia de tono','Marcas de rodillo','Chorreaduras','Encuentros sucios'],tip:'La pintura no corrige una mala preparación; la hace más visible.'}
};
const tips=[
'La calidad no se inspecciona al final: se construye durante el proceso.','Una observación repetida tres veces es un problema de sistema.','La siguiente cuadrilla es tu cliente interno.','Una partida ejecutada no es avance oficial hasta que Calidad la valide.','La mejor observación es la que nunca llega a existir.','Esperar materiales también es desperdicio Lean.','Mover materiales más veces de las necesarias agrega costo sin valor.','Un marco puede estar aplomado y aun así fuera de escuadra.','Las diagonales son una verificación rápida y efectiva.','La mayoría de filtraciones se produce en encuentros y cambios de plano.','El polvo es enemigo de la impermeabilización.','Una palmeta soplada rara vez mejora con el tiempo; normalmente empeora.','Una cantería constante es clave para la percepción visual.','Las sombras revelan desniveles que no se ven durante la instalación.','Un departamento entregado sin observaciones nace de cientos de decisiones correctas.','Un supervisor atento evita problemas para varias especialidades.','La limpieza influye directamente en la percepción de calidad.','Una restricción informada a tiempo no debe tratarse igual que un incumplimiento.','Ejecutado y validado son estados distintos.','La biblioteca no reemplaza el criterio: lo refuerza.','Cada revisión es una oportunidad para enseñar y aprender.','El avance real debe ser confiable, no optimista.','Cerrar una observación sin corregir solo traslada el problema.','La falta de información también es desperdicio.','La primera fila de cerámicos define la lectura visual del recinto.','Los rasgos de ventana son muy visibles para el cliente final.','Las pasadas de tuberías son puntos críticos de impermeabilización.','Las juntas de cornisa son más visibles de lo que parecen.','Corregir un marco antes de instalar la hoja cuesta minutos; después puede costar horas.','Las tolerancias acumuladas son más peligrosas que un error puntual.','Un tabique fuera de plomo afecta puertas, muebles y revestimientos.','El programa semanal debe mostrar problemas, no esconderlos.','Una papa caliente es una solicitud de gestión, no una observación técnica.','WhatsApp conversa; CheckObra deja trazabilidad.','Las notas personales ayudan al supervisor a no perder pendientes de terreno.'
];
let state={currentUser:null,route:'login',param:null,testMode:false,secretOpen:false,data:{states:{},checks:{},settings:{passwordsDisabled:false,notificationsEnabled:false},notifications:[],observations:[],program:[],papas:[],notes:[],history:[],qualityNotes:[],restrictions:[],documents:[],techNotices:[]}};
let historyStack=[], forwardStack=[];
function load(){try{const s=JSON.parse(localStorage.getItem('checkobra_v11_base_real'));if(s)state={...state,...s,data:{...state.data,...(s.data||{})}}}catch{}}
function save(){localStorage.setItem('checkobra_v11_base_real',JSON.stringify(state));syncCloud();}
let syncing=false; async function syncCloud(){if(!cloudReady||syncing)return;try{await setDoc(doc(db,'checkobra','v11_base_real'),{...state.data,updatedAt:serverTimestamp()},{merge:true})}catch(e){console.warn('No se pudo guardar en nube',e)}}
function listenCloud(){if(!cloudReady)return;onSnapshot(doc(db,'checkobra','v11_base_real'),snap=>{if(!snap.exists())return;syncing=true;const d=snap.data();delete d.updatedAt;state.data={...state.data,...d};localStorage.setItem('checkobra_v11_base_real',JSON.stringify(state));syncing=false;render();});}
function u(){return users.find(x=>x.id===state.currentUser)}
function go(route,param=null){if(state.route!==route)historyStack.push({route:state.route,param:state.param});forwardStack=[];state.route=route;state.param=param;save();render();}
function back(){const x=historyStack.pop();if(!x)return;forwardStack.push({route:state.route,param:state.param});state.route=x.route;state.param=x.param;save();render();}
function forward(){const x=forwardStack.pop();if(!x)return;historyStack.push({route:state.route,param:state.param});state.route=x.route;state.param=x.param;save();render();}
function home(){go('home')}
function keyOf(dept,part,room='DEPTO'){return `${dept}|${part}|${room}`}
function checkKey(dept,part,room='DEPTO'){return `ck|${dept}|${part}|${room}`}
function getChecks(dept,part,room='DEPTO'){return state.data.checks?.[checkKey(dept,part,room)]||[]}
function setCheck(dept,part,room,i,checked){if(!state.data.checks)state.data.checks={};const k=checkKey(dept,part,room);const arr=[...getChecks(dept,part,room)];arr[i]=!!checked;state.data.checks[k]=arr;return arr;}
function checklistComplete(part,arr){const total=(checklist[part]||[]).length;return total>0 && arr.filter(Boolean).length>=total;}
function checklistProgress(part,arr){const total=(checklist[part]||[]).length;return total?Math.round(arr.filter(Boolean).length/total*100):0;}
function notifyEvent(title,body,critical=false){try{state.data.notifications=state.data.notifications||[];state.data.notifications.unshift({id:Date.now(),title,body,critical,date:new Date().toLocaleString(),read:false});if(state.data.notifications.length>50)state.data.notifications.length=50;const audio=document.getElementById('alertSound'); if(audio){audio.currentTime=0;audio.play().catch(()=>{});} if(navigator.vibrate)navigator.vibrate(critical?[250,120,250]:[160]); if(state.data.settings?.notificationsEnabled && 'Notification' in window && Notification.permission==='granted'){new Notification(title,{body,icon:'assets/logo-aitue.png',tag:'checkobra-alerta'});} }catch(e){console.warn('Notificación local no disponible',e)}}
async function enableNotifications(){if(!('Notification' in window)){alert('Este navegador no soporta notificaciones.');return;}const perm=await Notification.requestPermission();state.data.settings=state.data.settings||{};state.data.settings.notificationsEnabled=perm==='granted';save();alert(perm==='granted'?'Notificaciones activadas':'No se autorizaron notificaciones');render();}
function togglePasswordView(){const e=document.getElementById('loginPass'); if(!e)return; e.type=e.type==='password'?'text':'password';}
function togglePasswordsDisabled(){if(u()?.id!=='paul')return;state.data.settings=state.data.settings||{};state.data.settings.passwordsDisabled=!state.data.settings.passwordsDisabled;save();render();}
function autoCheck(i){const {dept,part,room}=state.param;const arr=setCheck(dept,part,room,i,document.getElementById('ck'+i)?.checked);const pct=checklistProgress(part,arr);const cur=getState(dept,part,room);if(pct>0 && cur.status==='Sin iniciar'){setPartStatus(dept,part,room,'En ejecución',pct,'Inicio automático por primer check');notifyEvent('Partida iniciada',`${part} · Depto ${dept}`,false);return render();}if(checklistComplete(part,arr) && !['Ejecutada','Validada Calidad'].includes(cur.status)){setPartStatus(dept,part,room,'Ejecutada',100,'Liberada automáticamente por supervisor');notifyEvent('Partida liberada por supervisor',`${part} · Depto ${dept}`,true);return render();}setPartStatus(dept,part,room,cur.status==='Sin iniciar'?'En ejecución':cur.status,pct,cur.obs||'Guardado automático de checklist');render();}
function getState(dept,part,room='DEPTO'){return state.data.states[keyOf(dept,part,room)]||{status:'Sin iniciar',avance:0,dept,part,room,by:'',date:''}}

function depsMissing(dept,part){const req=dependencies[part]||[];return req.filter(dep=>{const st=getState(dept,dep,'DEPTO').status;return !['Ejecutada','Validada Calidad'].includes(st);});}
function canOverrideBlock(){return ['gonzalo','paul','vicente','cristobal'].includes(u().id);}
function setPartStatus(dept,part,room,status,av=0,obs=''){const cur=getState(dept,part,room);state.data.states[keyOf(dept,part,room)]={...cur,status,avance:Number(av),dept,part,room,by:u().name,date:new Date().toLocaleString(),obs};state.data.history.unshift({id:Date.now(),type:'estado',text:`${u().name} cambió ${part} Depto ${dept} ${room==='DEPTO'?'':room} a ${status}`,date:new Date().toLocaleString()});
if(['Observada','Ejecutada','Validada Calidad'].includes(status))notifyEvent(`Estado: ${status}`,`${part} · Depto ${dept} ${room==='DEPTO'?'':room}`,status==='Observada');if(status==='Ejecutada'){state.data.qualityNotes.unshift({id:Date.now(),from:u().name,dept,part,room,status:'Pendiente validación',date:new Date().toLocaleString()});}save();}
function deptMeta(dept){const f=Math.floor(dept/100), col=dept%100, type=typeByCol[col]||'A';return {floor:f,col,type,area:areaByType[type],rooms:typeRooms[type]||[]}}
function partApplies(part,rooms){if(deptLevelParts.includes(part))return ['DEPTO'];if(part==='Cerámicos Muro')return rooms.filter(r=>/baño|cocina/i.test(r));if(part==='Impermeabilización Baños'||part==='Vigones')return rooms.filter(r=>/baño/i.test(r));return rooms;}
function userParts(user=u()){return user.profile==='supervisor'?user.works:allParts}
function statusRank(s){return {'Sin iniciar':0,'En ejecución':1,'Ejecutada':2,'Validada Calidad':3,'Observada':-1}[s]??0}
function deptProgressFor(dept,parts=userParts()){const {rooms}=deptMeta(dept);let total=0, score=0, observed=false, exec=false;parts.forEach(p=>partApplies(p,rooms).forEach(r=>{total++;const st=getState(dept,p,r).status;if(st==='Observada')observed=true;if(st==='En ejecución'||st==='Ejecutada')exec=true;if(st==='Validada Calidad')score++;}));const pct=total?Math.round(score/total*100):0;let cls='gray',txt='Sin iniciar';if(observed){cls='red';txt='Observado'}else if(pct===100){cls='green';txt='Completado'}else if(exec||pct>0){cls='yellow';txt='En ejecución'}return {pct,cls,txt,total,score};}
function floorProgress(f,parts=userParts()){let max=f===2?5:6, sum=0;for(let c=1;c<=max;c++)sum+=deptProgressFor(f*100+c,parts).pct;return Math.round(sum/max)}
function observationsForUser(user=u()){return state.data.observations.filter(o=>o.resp===user.id&&o.status!=='Cerrada')}
function pendingProgramFor(user=u()){return state.data.program.filter(p=>p.resp===user.id&&!['Cumplido','Cancelado'].includes(p.status))}
function papasFor(user=u()){return state.data.papas.filter(p=>(p.to===user.id||p.to==='todos')&&p.status!=='Cerrada')}
function canManage(){return canAssign.includes(u().id)}
function canPapa(){return canCreatePapa.includes(u().id)}
function appShell(content){const user=u();const paulPanel=(user.id==='paul'&&state.secretOpen)?`<div class="secretPanel"><b>Panel Paul</b><button class="secondary" onclick="togglePasswordsDisabled()">${state.data.settings?.passwordsDisabled?'Activar contraseñas':'Deshabilitar contraseñas'}</button><button class="secondary" onclick="toggleTestMode()">${state.testMode?'Modo normal':'Modo prueba'}</button><select id="quickUser"><option value="">Cambiar usuario</option>${users.map(x=>`<option value="${x.id}">${x.name} · ${x.role}</option>`).join('')}</select><button class="secondary" onclick="quickSwitchUser()">Entrar al perfil</button></div>`:'';return `<header class="header"><img class="logo" src="assets/logo-aitue.png" onclick="secretTap()"><div><h1>CheckObra</h1><p>${user.name} · ${user.role}</p></div><button class="logout" onclick="logout()">Salir</button></header><main class="screen"><button class="secondary notifyBtn" onclick="enableNotifications()">🔔 Activar notificaciones y sonido</button>${content}${paulPanel}</main>${state.route==='login'?'':`<nav class="bottomNav"><button onclick="back()">◀</button><button onclick="home()">🏠</button><button onclick="forward()">▶</button></nav>`}`}
function loginView(){return `<header class="header"><img class="logo" src="assets/logo-aitue.png"><div><h1>CheckObra</h1><p>Castellón 227</p></div></header><main class="screen"><img class="hero" src="assets/castellon227.png"><h2>Ingreso</h2><p class="intro">Checklist, biblioteca técnica y control de avance de obra.</p><select id="loginUser">${users.map(x=>`<option value="${x.id}">${x.name} · ${x.role}</option>`).join('')}</select><div class="passRow"><input id="loginPass" type="password" placeholder="Clave de acceso"><button class="secondary smallBtn" onclick="togglePasswordView()">👁 Ver</button></div>${state.data.settings?.passwordsDisabled?'<p class="tip">Acceso sin contraseña activado por Paul.</p>':''}<button class="primary" onclick="login()">Entrar</button></main>`}
function homeView(){const user=u();if(user.profile==='supervisor')return supervisorHome(user);if(user.profile==='calidad')return calidadHome();if(user.profile==='gonzalo')return gonzaloHome();if(user.profile==='admin')return adminHome();if(user.profile==='oficina')return oficinaHome();return terrenoHome();}
function supervisorHome(user){return appShell(`<h2>Inicio · ${user.name}</h2><div class="kpi" onclick="go('observaciones')"><span>Observaciones por atender</span><b>${observationsForUser(user).length}</b></div><div class="kpi" onclick="go('programa')"><span>Compromisos pendientes</span><b>${pendingProgramFor(user).length}</b></div><div class="kpi" onclick="go('papas')"><span>Papas activas</span><b>${papasFor(user).length}</b></div><div class="grid"><button class="card" onclick="go('misPartidas')">🏗 Mis partidas</button><button class="card" onclick="go('edificio')">🏢 Estado edificio</button><button class="card" onclick="go('programa')">📅 Mis compromisos</button><button class="card" onclick="go('papas')">🥔 Papas</button><button class="card" onclick="go('biblioteca')">📚 Biblioteca</button><button class="card" onclick="go('documentos')">📂 Documentos</button><button class="card" onclick="go('notas')">📝 Mis notas</button></div>`)}
function calidadHome(){return appShell(`<h2>Inicio · Vicente Bizama</h2><div class="kpi" onclick="go('centroCalidad')"><span>Avisos pendientes</span><b>${state.data.qualityNotes.filter(n=>n.status!=='Cerrada').length}</b></div><div class="kpi" onclick="go('observaciones')"><span>Observaciones abiertas</span><b>${state.data.observations.filter(o=>o.status!=='Cerrada').length}</b></div><div class="kpi" onclick="go('centroCalidad')"><span>Listas para validar</span><b>${state.data.qualityNotes.filter(n=>n.status==='Pendiente validación').length}</b></div><div class="grid"><button class="card" onclick="go('centroCalidad')">✅ Centro Calidad</button><button class="card" onclick="go('edificio')">🏢 Auditar edificio</button><button class="card" onclick="go('observaciones')">🔴 Observaciones</button><button class="card" onclick="go('historial')">📋 Historial Calidad</button><button class="card" onclick="go('papas')">🥔 Papas</button><button class="card" onclick="go('biblioteca')">📚 Biblioteca</button><button class="card" onclick="go('documentos')">📂 Documentos</button></div>`)}
function gonzaloHome(){const sup=users.filter(x=>x.profile==='supervisor');return appShell(`<h2>Inicio · Gonzalo Riquelme</h2><div class="kpi" onclick="go('programa')"><span>Cumplimiento semanal</span><b>${weeklyPct()}%</b></div><div class="kpi" onclick="go('atrasos')"><span>Atrasos según programa</span><b>${latePrograms().length}</b></div><div class="kpi" onclick="go('observaciones')"><span>Observaciones abiertas</span><b>${state.data.observations.filter(o=>o.status!=='Cerrada').length}</b></div><div class="kpi" onclick="go('papas')"><span>Papas activas</span><b>${state.data.papas.filter(p=>p.status!=='Cerrada').length}</b></div><h3>Supervisores</h3>${sup.map(s=>`<div class="partRow" onclick="go('supervisorDetalle','${s.id}')"><b>${s.name}</b><span class="tag ${programPct(s.id)>85?'ok':programPct(s.id)>70?'warn':'bad'}">${programPct(s.id)}%</span></div>`).join('')}<div class="grid"><button class="card" onclick="go('prioridades')">🎯 Prioridades</button><button class="card" onclick="go('programa')">📅 Programa semanal</button><button class="card" onclick="go('centroCalidad')">✅ Calidad</button><button class="card" onclick="go('edificio')">🏢 Estado edificio</button><button class="card" onclick="go('papas')">🥔 Papas</button><button class="card" onclick="go('biblioteca')">📚 Biblioteca</button><button class="card" onclick="go('documentos')">📂 Documentos</button></div>`)}
function adminHome(){return appShell(`<h2>Dashboard Ejecutivo · Cristóbal</h2>${dashboardKpis()}<h3>Centro de Gestión</h3>${graphBlock('Programado vs Ejecutado', supervisorBars())}${graphBlock('Avance por piso', floorBars())}${graphBlock('Ejecutado vs Validado', executedValidatedBars())}<div class="grid"><button class="card" onclick="go('centroGestion')">🎯 Centro Gestión</button><button class="card" onclick="go('programa')">📅 Programa semanal</button><button class="card" onclick="go('edificio')">🏢 Estado Obra</button><button class="card" onclick="go('restricciones')">🚧 Restricciones</button><button class="card" onclick="go('papas')">🥔 Papas</button><button class="card" onclick="go('observaciones')">🔴 Observaciones</button><button class="card" onclick="go('reportes')">📊 Reportes</button><button class="card" onclick="go('biblioteca')">📚 Biblioteca</button><button class="card" onclick="go('documentos')">📂 Documentos</button></div>`)}
function terrenoHome(){return appShell(`<h2>Inicio · Paul González</h2>${dashboardKpis(true)}<div class="kpi"><span>Frentes disponibles</span><b>${availableFronts()}</b></div><div class="grid"><button class="card" onclick="go('edificio')">🏗 Estado Obra</button><button class="card" onclick="go('programa')">📅 Programa semanal</button><button class="card" onclick="go('restricciones')">🚧 Restricciones</button><button class="card" onclick="go('observaciones')">🔴 Observaciones</button><button class="card" onclick="go('papas')">🥔 Papas</button><button class="card" onclick="go('centroCalidad')">✅ Calidad</button><button class="card" onclick="go('biblioteca')">📚 Biblioteca</button><button class="card" onclick="go('documentos')">📂 Documentos</button><button class="card" onclick="go('reportes')">📊 Reportes</button></div>`)}
function oficinaHome(){return appShell(`<h2>Inicio · Constanza Reyes</h2><div class="kpi"><span>Documentos vigentes</span><b>${state.data.documents.filter(d=>d.status==='Vigente').length}</b></div><div class="kpi"><span>RDI pendientes</span><b>${state.data.documents.filter(d=>d.type==='RDI'&&d.status!=='Cerrada').length}</b></div><div class="kpi"><span>Comunicados técnicos</span><b>${state.data.techNotices.length}</b></div><div class="grid"><button class="card" onclick="go('documentos')">📂 Documentos</button><button class="card" onclick="go('documentos','Plano')">📄 Planos</button><button class="card" onclick="go('documentos','Protocolo')">📋 Protocolos</button><button class="card" onclick="go('documentos','RDI')">📌 RDI / Consultas</button><button class="card" onclick="go('documentos','Ficha Técnica')">📚 Fichas técnicas</button><button class="card" onclick="go('comunicadosTecnicos')">📢 Comunicados técnicos</button><button class="card" onclick="go('biblioteca')">📚 Biblioteca</button><button class="card" onclick="go('reportes')">📊 Reportes</button></div>`)}
function dashboardKpis(){return `<div class="two"><div class="kpi" onclick="go('edificio')"><span>Avance validado</span><b>${validatedPct()}%</b></div><div class="kpi" onclick="go('programa')"><span>Cumplimiento semanal</span><b>${weeklyPct()}%</b></div><div class="kpi" onclick="go('observaciones')"><span>Obs. abiertas</span><b>${state.data.observations.filter(o=>o.status!=='Cerrada').length}</b></div><div class="kpi" onclick="go('restricciones')"><span>Restricciones</span><b>${state.data.restrictions.filter(r=>r.status!=='Cerrada').length}</b></div></div>`}
function graphBlock(title,rows){return `<div class="item"><b>${title}</b>${rows}</div>`}
function bar(label,pct){return `<div><div class="partRow"><span>${label}</span><b>${pct}%</b></div><div class="bar"><span style="width:${pct}%"></span></div></div>`}
function supervisorBars(){return users.filter(x=>x.profile==='supervisor').map(s=>bar(s.name,programPct(s.id))).join('')}
function floorBars(){let h='';for(let f=2;f<=17;f++)h+=`<details class="floorDetail"><summary>Piso ${f} · ${floorProgress(f,allParts)}%</summary>${bar('Avance validado',floorProgress(f,allParts))}</details>`;return h}
function executedValidatedBars(){return bar('Ejecutado',executedPct())+bar('Validado Calidad',validatedPct())}
function weeklyPct(){const p=state.data.program.filter(x=>x.status!=='Cancelado');if(!p.length)return 0;return Math.round(p.filter(x=>x.status==='Cumplido').length/p.length*100)}
function programPct(id){const p=state.data.program.filter(x=>x.resp===id&&x.status!=='Cancelado');if(!p.length)return 0;return Math.round(p.filter(x=>x.status==='Cumplido').length/p.length*100)}
function latePrograms(){return state.data.program.filter(p=>p.status==='Atrasado')}
function allStateEntries(){return Object.values(state.data.states)}
function validatedPct(){const e=allStateEntries();if(!e.length)return 0;return Math.round(e.filter(x=>x.status==='Validada Calidad').length/e.length*100)}
function executedPct(){const e=allStateEntries();if(!e.length)return 0;return Math.round(e.filter(x=>['Ejecutada','Validada Calidad'].includes(x.status)).length/e.length*100)}
function availableFronts(){let n=0;for(let f=2;f<=17;f++){let max=f===2?5:6;for(let c=1;c<=max;c++){if(deptProgressFor(f*100+c,allParts).pct<100)n++}}return n}
function misPartidas(){const user=u();return appShell(`<h2>Mis partidas</h2>${user.works.map(p=>`<button class="item" style="width:100%;text-align:left" onclick="go('edificio','${p}')"><b>${p}</b><br><span class="muted">Checklist, biblioteca y avance asociado</span></button>`).join('')}`)}
function edificio(){const selectedPart=state.param;const user=u();let parts=(selectedPart? [selectedPart] : (user.profile==='supervisor'?user.works:allParts));let title=user.profile==='supervisor'&&!selectedPart?'Estado edificio · mis partidas': selectedPart?`Estado edificio · ${selectedPart}`:'Auditar edificio';let h=`<h2>${title}</h2><p class="intro">Estado visual por piso y departamento.</p><div class="legend"><span><i class="dot gray"></i> Sin iniciar</span><span><i class="dot yellow"></i> En ejecución</span><span><i class="dot blue"></i> Ejecutada</span><span><i class="dot green"></i> Validada</span><span><i class="dot red"></i> Observada</span></div>`;for(let f=2;f<=17;f++){let max=f===2?5:6;h+=`<details class="floor" ${f<=4?'open':''}><summary>Piso ${f} · Avance ${floorProgress(f,parts)}%</summary><div class="floorGrid">`;for(let c=1;c<=max;c++){let d=f*100+c, st=deptProgressFor(d,parts);h+=`<button class="deptBtn state-${st.cls}" onclick="go('depto',{dept:${d},part:${selectedPart?`'${selectedPart}'`:'null'}})">${d}</button>`}h+=`</div></details>`}return appShell(h)}
function depto(){const {dept,part}=state.param||{};const meta=deptMeta(dept);const user=u();let parts=part?[part]:(user.profile==='supervisor'?user.works:allParts);let st=deptProgressFor(dept,parts);let h=`<h2>Depto ${dept}</h2><p class="intro">Piso ${meta.floor} · Tipo ${meta.type} · ${meta.area}</p><div class="kpi"><span>Estado departamento</span><b>${st.txt}</b></div>`;
if(part){h+=`<h3>${part}</h3>`;let targets=partApplies(part,meta.rooms);targets.forEach(r=>{const s=getState(dept,part,r);h+=`<div class="partRow"><span>${r==='DEPTO'?'Control por departamento':r}<br><small class="mini">${s.status}</small></span><button onclick="go('revision',{dept:${dept},part:'${part}',room:'${r}'})">Abrir checklist</button></div>`});}
else{h+=`<h3>${user.profile==='calidad'||user.profile==='admin'||user.profile==='terreno'||user.profile==='gonzalo'?'Todas las partidas del departamento':'Estado de mis partidas'}</h3>`;parts.forEach(p=>{let targets=partApplies(p,meta.rooms), vals=targets.map(r=>getState(dept,p,r).status);let status=vals.includes('Observada')?'Observada':vals.every(x=>x==='Validada Calidad')?'Validada Calidad':vals.includes('Ejecutada')?'Ejecutada':vals.includes('En ejecución')?'En ejecución':'Sin iniciar';h+=`<div class="partRow"><span><b>${p}</b><br><small>${targets.length>1?targets.length+' controles':(targets[0]==='DEPTO'?'Control por departamento':targets[0])}</small></span><span class="tag ${status==='Validada Calidad'?'ok':status==='Observada'?'bad':status==='Ejecutada'?'blue':status==='En ejecución'?'warn':''}">${status}</span><button onclick="go('depto',{dept:${dept},part:'${p}'})">Ver</button></div>`})}
return appShell(h)}
function revision(){const {dept,part,room}=state.param;const s=getState(dept,part,room);const user=u();const isQuality=user.id==='vicente';const missing=depsMissing(dept,part);const blocked=missing.length&&!canOverrideBlock();const checks=getChecks(dept,part,room);let blocker=missing.length?`<div class="item hot"><b>🔒 Partida bloqueada por dependencias constructivas</b><br>Pendientes: ${missing.map(x=>`<span class="tag bad">${x}</span>`).join(' ')}<br><small>Solo Gonzalo, Paul, Vicente o Cristóbal pueden liberar excepcionalmente.</small></div>`:'';let saveBtn=blocked?`<button class="danger" onclick="alert('No se puede guardar avance hasta liberar dependencias.')">Bloqueado</button>`:`<button class="primary" onclick="saveReview()">Guardar comentario/estado manual</button>`;let tol=library[part]?.tol?.slice(0,5).map(x=>`<li>${x}</li>`).join('')||'<li>Sin tolerancias cargadas.</li>';let h=`<h2>${part}</h2><p class="intro">Depto ${dept} · ${room==='DEPTO'?'Control por departamento':room}</p>${blocker}<div class="kpi"><span>Estado actual</span><b>${s.status}</b></div><div class="item info"><b>📐 Tolerancias numéricas / control</b><ul>${tol}</ul></div><h3>Checklist con guardado automático</h3><p class="intro">Cada check queda guardado al instante. Primer check inicia la partida; último check la libera por supervisor.</p><div class="checklistBox">${(checklist[part]||[]).map((x,i)=>`<label class="item"><input type="checkbox" id="ck${i}" ${checks[i]?'checked':''} onchange="autoCheck(${i})" ${blocked?'disabled':''}><span>${x}</span></label>`).join('')}</div><h3>Actualizar estado manual</h3><select id="revState">${stateOrder.filter(x=>isQuality||!['Validada Calidad','Observada'].includes(x)).map(x=>`<option ${x===s.status?'selected':''}>${x}</option>`).join('')}</select><label class="rangeLabel">Avance declarado: <b id="revAvLabel">${s.avance||0}%</b></label><input id="revAv" type="range" min="0" max="100" step="25" value="${s.avance||0}" oninput="updateRangeLabel()"><textarea id="revObs" placeholder="Comentario, observación o respaldo">${s.obs||''}</textarea>${saveBtn}`;
if(isQuality)h+=`<h3>Acciones Calidad</h3><div class="two"><button class="btn" onclick="qualityApprove()">Validar Calidad</button><button class="danger" onclick="qualityObserve()">Observar</button></div>`;return appShell(h)}
function updateRangeLabel(){const e=document.getElementById('revAvLabel');if(e)e.innerText=(document.getElementById('revAv')?.value||0)+'%'}
function saveReview(){const {dept,part,room}=state.param;setPartStatus(dept,part,room,document.getElementById('revState').value,document.getElementById('revAv').value,document.getElementById('revObs').value);alert('Revisión guardada');go('depto',{dept,part:null})}
function qualityApprove(){const {dept,part,room}=state.param;setPartStatus(dept,part,room,'Validada Calidad',100,'Validado por Calidad');state.data.qualityNotes=state.data.qualityNotes.map(n=>n.dept==dept&&n.part===part&&n.room===room?{...n,status:'Cerrada'}:n);save();alert('Avance validado por Calidad');go('centroCalidad')}
function qualityObserve(){const {dept,part,room}=state.param;const detail=prompt('Detalle de observación');if(!detail)return;setPartStatus(dept,part,room,'Observada',0,detail);let resp=responsibleFor(part);state.data.observations.unshift({id:Date.now(),by:u().id,byName:u().name,resp,dept,part,room,severity:'Crítica',text:detail,status:'Abierta',date:new Date().toLocaleString()});save();alert('Observación creada');go('centroCalidad')}
function responsibleFor(part){return users.find(x=>x.profile==='supervisor'&&x.works.includes(part))?.id||'nicole'}
function programa(){const user=u();if(!canManage())return appShell(`<h2>Mis compromisos</h2><div class="tabs"><button class="active">Pendientes</button><button onclick="go('programaHist')">Historial</button></div>${programList(state.data.program.filter(p=>p.resp===user.id&&!['Cumplido','Cancelado'].includes(p.status)))}`);const active=filteredPrograms().filter(p=>!['Cumplido','Cancelado'].includes(p.status));const done=filteredPrograms().filter(p=>['Cumplido','Cancelado'].includes(p.status));return appShell(`<h2>Programa semanal</h2><div class="item"><select id="progPart">${allParts.map(p=>`<option>${p}</option>`)}</select><select id="progResp">${users.filter(x=>x.profile==='supervisor').map(s=>`<option value="${s.id}">${s.name}</option>`)}</select><input id="progFloor" type="number" placeholder="Piso, ejemplo 4"><input id="progRange" placeholder="Deptos, ejemplo 401-404 o 401,402"><select id="progDay">${['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'].map(d=>`<option>${d}</option>`)}</select><textarea id="progNote" placeholder="Observación / meta"></textarea><button class="primary" onclick="addProgram()">Agregar compromiso</button></div><h3>Filtrar por supervisor</h3><select id="progFilter" onchange="render()"><option value="todos">Todos</option>${users.filter(x=>x.profile==='supervisor').map(s=>`<option value="${s.id}">${s.name}</option>`)}</select><h3>Pendientes / En ejecución</h3>${programList(active)}<details class="item"><summary><b>Historial cumplidos (${done.length})</b></summary>${programList(done)}</details>`)}
function filteredPrograms(){let f=document.getElementById('progFilter')?.value||'todos';return f==='todos'?state.data.program:state.data.program.filter(p=>p.resp===f)}
function programList(list){return list.length?list.map(p=>`<div class="item"><b>${p.day} · ${p.part}</b><br>Piso ${p.floor} · Deptos ${p.range}<br>Responsable: ${users.find(u=>u.id===p.resp)?.name}<br><span class="tag ${p.status==='Cumplido'?'ok':p.status==='Atrasado'?'bad':p.status==='Restringido'?'warn':'blue'}">${p.status}</span><div class="bar"><span style="width:${p.avance||0}%"></span></div><small>${p.note||''}</small><div class="two">${u().id===p.resp?`<button class="btn" onclick="acceptProgram(${p.id})">Aceptar / avance</button><button class="secondary" onclick="restrictProgram(${p.id})">Informar restricción</button>`:''}${canManage()?`<button class="btn" onclick="markProgram(${p.id},'Cumplido')">Cumplido</button><button class="danger" onclick="markProgram(${p.id},'Atrasado')">Atrasado</button>`:''}</div></div>`).join(''):'<p class="intro">Sin compromisos.</p>'}
function addProgram(){state.data.program.unshift({id:Date.now(),part:v('progPart'),resp:v('progResp'),floor:v('progFloor'),range:v('progRange'),day:v('progDay'),note:v('progNote'),status:'Pendiente aceptación',avance:0,date:new Date().toLocaleString(),by:u().id});save();render()}
function acceptProgram(id){let av=prompt('Avance del compromiso (%)','0');state.data.program=state.data.program.map(p=>p.id===id?{...p,status:Number(av)>=100?'Cumplido':'En ejecución',avance:Number(av)}:p);save();render()}
function restrictProgram(id){let reason=prompt('Motivo restricción: material, plano, especialidad previa, mano de obra, suministro u otro');if(!reason)return;state.data.program=state.data.program.map(p=>p.id===id?{...p,status:'Restringido',restriction:reason}:p);state.data.restrictions.unshift({id:Date.now(),source:'programa',programId:id,reason,status:'Abierta',by:u().id,date:new Date().toLocaleString()});save();render()}
function markProgram(id,status){state.data.program=state.data.program.map(p=>p.id===id?{...p,status,avance:status==='Cumplido'?100:p.avance}:p);save();render()}
function programaHist(){return appShell(`<h2>Historial compromisos</h2>${programList(state.data.program.filter(p=>p.resp===u().id&&['Cumplido','Cancelado'].includes(p.status)))}`)}
function papas(){let list=papasFor(u());if(canPapa())list=state.data.papas;return appShell(`<h2>Papas frías, tibias y calientes</h2>${canPapa()?`<div class="item"><select id="papaTo"><option value="todos">Todos</option>${users.filter(x=>x.profile==='supervisor').map(s=>`<option value="${s.id}">${s.name}</option>`)}</select><select id="papaUrg"><option>Caliente</option><option>Tibia</option><option>Fría</option></select><input id="papaTitle" placeholder="Título"><textarea id="papaBody" placeholder="Solicitud"></textarea><button class="primary" onclick="addPapa()">Crear papa</button></div>`:''}${['Caliente','Tibia','Fría'].map(t=>`<h3>${t==='Caliente'?'🔴':t==='Tibia'?'🟡':'🟢'} Papas ${t}s</h3>${papaList(list.filter(p=>p.urgency===t))}`).join('')}`)}
function papaList(list){return list.length?list.map(p=>`<div class="item ${p.urgency==='Caliente'?'hot':p.urgency==='Tibia'?'warm':'cold'}"><b>${p.title}</b><br>${p.body}<br><small>Solicita: ${users.find(x=>x.id===p.by)?.name||p.by} · Para: ${p.to==='todos'?'Todos':users.find(x=>x.id===p.to)?.name}</small><br><span class="tag">${p.status}</span>${p.status!=='Cerrada'?`<button class="secondary" onclick="closePapa(${p.id})">Marcar atendida</button>`:''}</div>`).join(''):'<p class="intro">Sin papas.</p>'}
function addPapa(){state.data.papas.unshift({id:Date.now(),to:v('papaTo'),urgency:v('papaUrg'),title:v('papaTitle'),body:v('papaBody'),by:u().id,status:'Pendiente',date:new Date().toLocaleString()});save();render()}
function closePapa(id){state.data.papas=state.data.papas.map(p=>p.id===id?{...p,status:'Cerrada'}:p);save();render()}
function observaciones(){let list=u().profile==='supervisor'?observationsForUser(u()):state.data.observations.filter(o=>o.status!=='Cerrada');return appShell(`<h2>Observaciones</h2>${list.map(o=>`<div class="item hot"><b>${o.part} · Depto ${o.dept}</b><br>${o.room==='DEPTO'?'Control por departamento':o.room}<br>${o.text}<br><small>Observó: ${users.find(x=>x.id===o.by)?.name||o.by} · Resp: ${users.find(x=>x.id===o.resp)?.name}</small><br><span class="tag bad">${o.severity}</span><span class="tag">${o.status}</span>${o.resp===u().id?`<button class="secondary" onclick="obsProcess(${o.id})">Marcar en proceso</button>`:''}${u().id==='vicente'?`<button class="btn" onclick="closeObs(${o.id})">Cerrar</button>`:''}</div>`).join('')||'<p class="intro">Sin observaciones abiertas.</p>'}`)}
function obsProcess(id){state.data.observations=state.data.observations.map(o=>o.id===id?{...o,status:'En proceso'}:o);save();render()}
function closeObs(id){state.data.observations=state.data.observations.map(o=>o.id===id?{...o,status:'Cerrada'}:o);save();render()}
function centroCalidad(){const notes=state.data.qualityNotes.filter(n=>n.status!=='Cerrada');return appShell(`<h2>Centro Calidad</h2><h3>Pendientes de validación</h3>${notes.map(n=>`<div class="item info"><b>${n.part} · Depto ${n.dept}</b><br>${n.room==='DEPTO'?'Control por departamento':n.room}<br>Informa: ${n.from}<br><span class="tag blue">${n.status}</span><button class="btn" onclick="go('revision',{dept:${n.dept},part:'${n.part}',room:'${n.room}'})">Revisar</button></div>`).join('')||'<p class="intro">Sin pendientes de calidad.</p>'}`)}
function biblioteca(){let q=(document.getElementById('libQ')?.value||'').toLowerCase();let entries=Object.entries(library).filter(([k,d])=>(k+' '+d.doc+' '+d.inst.join(' ')+' '+d.tol.join(' ')+' '+d.fullTol.join(' ')+' '+d.method.join(' ')+' '+d.err.join(' ')+' '+d.tip).toLowerCase().includes(q));return appShell(`<h2>Biblioteca del Saber</h2><input id="libQ" placeholder="Buscar partida o tolerancia..." oninput="render()" value="${q}"><div class="tip">💡 <b>¿Sabías que?</b><br>${tips[Math.floor(Math.random()*tips.length)]}</div><button class="secondary" onclick="render()" style="width:100%">Nuevo tip aleatorio</button><div class="lib">${entries.map(([k,d])=>`<details><summary>${k}</summary><div class="item"><b>📏 Instrumentos</b><ul>${d.inst.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="item"><b>📐 Tolerancias clave</b><ul>${d.tol.map(x=>`<li>${x}</li>`).join('')}</ul><details class="subdetails"><summary>Ver tolerancias completas</summary><ul>${d.fullTol.map(x=>`<li>${x}</li>`).join('')}</ul></details></div><div class="item"><b>🔍 Cómo revisar</b><ol>${d.method.map(x=>`<li>${x}</li>`).join('')}</ol></div><div class="item"><b>⚠️ Errores frecuentes</b><ul>${d.err.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="tip"><b>💡 Sabías que...</b><br>${d.tip}</div></details>`).join('')}</div>`)}
function notas(){let list=state.data.notes.filter(n=>n.user===u().id);return appShell(`<h2>Mis notas</h2><div class="item"><textarea id="noteBody" placeholder="Nueva nota personal..."></textarea><button class="primary" onclick="addNote()">Agregar nota</button></div>${list.map(n=>`<div class="item"><label><input type="checkbox" ${n.done?'checked':''} onchange="toggleNote(${n.id})"> ${n.body}</label><br><small>${n.date}</small><button class="danger" onclick="deleteNote(${n.id})">Eliminar</button></div>`).join('')||'<p class="intro">Sin notas personales.</p>'}`)}
function addNote(){if(!v('noteBody'))return;state.data.notes.unshift({id:Date.now(),user:u().id,body:v('noteBody'),done:false,date:new Date().toLocaleString()});save();render()}
function toggleNote(id){state.data.notes=state.data.notes.map(n=>n.id===id?{...n,done:!n.done}:n);save();render()}
function deleteNote(id){state.data.notes=state.data.notes.filter(n=>n.id!==id);save();render()}

function documentos(){const filter=state.param;const docs=state.data.documents.filter(d=>!filter||d.type===filter);const canAdd=['paul','cristobal','constanza','gonzalo','vicente'].includes(u().id);const canDelete=['paul','cristobal','constanza'].includes(u().id);return appShell(`<h2>${filter||'Documentos'}</h2>${canAdd?`<div class="item"><select id="docType"><option>Plano</option><option>Protocolo</option><option>RDI</option><option>Ficha Técnica</option><option>Procedimiento</option><option>Certificado</option><option>Acta</option><option>Informe</option><option>Fotografía</option></select><input id="docTitle" placeholder="Nombre del documento"><input id="docFile" type="file"><input id="docRef" placeholder="Link, código o referencia"><select id="docStatus"><option>Vigente</option><option>Reemplazado</option><option>Obsoleto</option><option>Pendiente</option><option>Cerrada</option></select><button class="primary" onclick="addDocument()">Subir documento</button></div>`:''}${docs.map(d=>`<div class="item"><b>${d.title}</b><br><span class="tag blue">${d.type}</span><span class="tag ${d.status==='Vigente'?'ok':d.status==='Obsoleto'?'bad':'warn'}">${d.status}</span><br><small>${d.ref||''}</small>${d.fileData?`<br><a class="docLink" href="${d.fileData}" target="_blank">Abrir archivo</a>`:''}<br><small>Subido por ${d.by} · ${d.date}</small>${canDelete?`<br><button class="danger" onclick="deleteDocument(${d.id})">Eliminar</button>`:''}</div>`).join('')||'<p class="intro">Sin documentos registrados.</p>'}`)}
function addDocument(){if(!v('docTitle'))return;const file=document.getElementById('docFile')?.files?.[0];const base={id:Date.now(),type:v('docType'),title:v('docTitle'),ref:v('docRef')||(file?file.name:''),status:v('docStatus'),by:u().name,date:new Date().toLocaleString()};if(file){const reader=new FileReader();reader.onload=()=>{state.data.documents.unshift({...base,fileName:file.name,fileData:reader.result});save();render()};reader.readAsDataURL(file);return;}state.data.documents.unshift(base);save();render()}
function deleteDocument(id){state.data.documents=state.data.documents.filter(d=>d.id!==id);save();render()}
function comunicadosTecnicos(){return appShell(`<h2>Comunicados técnicos</h2><div class="item"><input id="noticeTitle" placeholder="Título comunicado"><textarea id="noticeBody" placeholder="Información importante para terreno"></textarea><button class="primary" onclick="addTechNotice()">Publicar comunicado</button></div>${state.data.techNotices.map(n=>`<div class="item info"><b>${n.title}</b><br>${n.body}<br><small>${n.by} · ${n.date}</small></div>`).join('')||'<p class="intro">Sin comunicados técnicos.</p>'}`)}
function addTechNotice(){if(!v('noticeTitle'))return;state.data.techNotices.unshift({id:Date.now(),title:v('noticeTitle'),body:v('noticeBody'),by:u().name,date:new Date().toLocaleString()});save();render()}
function prioridades(){return centroGestion('Prioridades')}
function centroGestion(title='Centro Gestión'){return appShell(`<h2>${title}</h2><div class="item hot click" onclick="go('atrasos')"><b>Atrasos</b><br>${latePrograms().length} compromisos atrasados.</div><div class="item hot click" onclick="go('observaciones')"><b>Observaciones críticas</b><br>${state.data.observations.filter(o=>o.status!=='Cerrada'&&o.severity==='Crítica').length} abiertas.</div><div class="item warm click" onclick="go('restricciones')"><b>Restricciones</b><br>${state.data.restrictions.filter(r=>r.status!=='Cerrada').length} activas.</div><div class="item hot click" onclick="go('papas')"><b>Papas calientes</b><br>${state.data.papas.filter(p=>p.status!=='Cerrada'&&p.urgency==='Caliente').length} sin atender.</div><div class="item info click" onclick="go('centroCalidad')"><b>Pendientes de calidad</b><br>${state.data.qualityNotes.filter(n=>n.status!=='Cerrada').length} listas para validar.</div>`)}
function atrasos(){return appShell(`<h2>Atrasos según programa</h2>${programList(latePrograms())}`)}
function restricciones(){return appShell(`<h2>Restricciones</h2>${state.data.restrictions.map(r=>`<div class="item warm"><b>${r.reason}</b><br>${r.status}<br><small>${r.date}</small><button class="secondary" onclick="closeRestriction(${r.id})">Cerrar</button></div>`).join('')||'<p class="intro">Sin restricciones activas.</p>'}`)}
function closeRestriction(id){state.data.restrictions=state.data.restrictions.map(r=>r.id===id?{...r,status:'Cerrada'}:r);save();render()}
function historial(){return appShell(`<h2>Historial</h2>${state.data.history.map(h=>`<div class="item"><b>${h.text}</b><br><small>${h.date}</small></div>`).join('')||'<p class="intro">Sin historial.</p>'}`)}
function reportes(){return appShell(`<h2>Reportes</h2><div class="item"><b>Calidad primera pasada</b><br>${firstPass()}%</div><div class="item"><b>Edad observaciones</b><br>0-3 días: ${state.data.observations.filter(o=>o.status!=='Cerrada').length}<br>4-7 días: 0<br>+7 días: 0</div><div class="item"><b>Top partidas problemáticas</b><br>${topObserved()}</div>`)}
function produccion(){return appShell(`<h2>Producción</h2>${graphBlock('Producción por supervisor', supervisorBars())}${graphBlock('Producción por piso', floorBars())}`)}
function firstPass(){const obs=state.data.observations.length, val=allStateEntries().filter(x=>x.status==='Validada Calidad').length;return val+obs?Math.round(val/(val+obs)*100):100}
function topObserved(){const m={};state.data.observations.forEach(o=>m[o.part]=(m[o.part]||0)+1);return Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([k,v])=>`${k}: ${v}`).join('<br>')||'Sin datos'}
function supervisorDetalle(id){const s=users.find(x=>x.id===id);return appShell(`<h2>${s.name}</h2><div class="kpi"><span>Cumplimiento</span><b>${programPct(id)}%</b></div><div class="kpi"><span>Compromisos pendientes</span><b>${pendingProgramFor(s).length}</b></div><div class="kpi" onclick="go('observaciones')"><span>Obs. abiertas</span><b>${observationsForUser(s).length}</b></div><div class="kpi"><span>Papas</span><b>${papasFor(s).length}</b></div>`)}
function seed(){if(localStorage.getItem('checkobra_v11_base_real_seed'))return;state.data={states:{},checks:{},settings:{passwordsDisabled:false,notificationsEnabled:false},notifications:[],observations:[],program:[],papas:[],notes:[],history:[],qualityNotes:[],restrictions:[],documents:[],techNotices:[]};localStorage.setItem('checkobra_v11_base_real_seed','1');save()}
function login(){const selected=users.find(x=>x.id===v('loginUser'));const passOk=selected&&(state.testMode||state.data.settings?.passwordsDisabled||selected.pass===v('loginPass'));if(!passOk){alert('Clave incorrecta');return}state.currentUser=selected.id;state.route='home';save();render()}
function logout(){state.currentUser=null;state.route='login';save();render()}
function v(id){return document.getElementById(id)?.value||''}
function render(){const app=document.getElementById('app');if(!state.currentUser||state.route==='login'){app.innerHTML=loginView();return}const routes={home:homeView,misPartidas,edificio,depto,revision,programa,programaHist,papas,observaciones,centroCalidad,biblioteca,notas,prioridades,centroGestion,restricciones,historial,reportes,produccion,atrasos,supervisorDetalle,documentos,comunicadosTecnicos};app.innerHTML=(routes[state.route]||homeView)(state.param)}
window.enableNotifications=enableNotifications;window.togglePasswordView=togglePasswordView;window.togglePasswordsDisabled=togglePasswordsDisabled;window.autoCheck=autoCheck;window.login=login;window.logout=logout;window.toggleTestMode=toggleTestMode;window.quickSwitchUser=quickSwitchUser;window.go=go;window.back=back;window.forward=forward;window.home=home;window.saveReview=saveReview;window.qualityApprove=qualityApprove;window.qualityObserve=qualityObserve;window.addProgram=addProgram;window.acceptProgram=acceptProgram;window.restrictProgram=restrictProgram;window.markProgram=markProgram;window.addPapa=addPapa;window.closePapa=closePapa;window.obsProcess=obsProcess;window.closeObs=closeObs;window.addNote=addNote;window.toggleNote=toggleNote;window.deleteNote=deleteNote;window.closeRestriction=closeRestriction;window.addDocument=addDocument;window.addTechNotice=addTechNotice;window.render=render;window.updateRangeLabel=updateRangeLabel;window.secretTap=secretTap;window.deleteDocument=deleteDocument;


let secretTapCount=0, secretTapTimer=null;
function secretTap(){if(!state.currentUser||state.currentUser!=='paul')return;secretTapCount++;clearTimeout(secretTapTimer);secretTapTimer=setTimeout(()=>secretTapCount=0,1200);if(secretTapCount>=5){state.secretOpen=!state.secretOpen;secretTapCount=0;save();render();}}
function toggleTestMode(){state.testMode=!state.testMode;save();render()}
function quickSwitchUser(){const id=v('quickUser');if(!id)return;state.currentUser=id;state.route='home';save();render()}
load();seed();listenCloud();render();
